### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by northkode** [benallfree/cordova-live-update#1]
You dont really go into detail on how to get the LiveUpdate Class into the cordova app.. 
looks like it requires alot of files.. how are those loaded in etc..

**Comment by BenitoP** [comment]
@northkode Did you ever manage to get this working?

**Comment by benallfree** [comment]
I'd be glad to have some help, I'm rebooting this project.

**Comment by northkode** [comment]
@BenitoP i did not, sorry didnt see the reply. I ended up using microsoft code push.
