### ISSUE TITLE
updating content?

### ISSUE THREAD

**Issue by kwv** [benallfree/cordova-live-update#2]
Thanks for the work to put this together.  We're trialing cordova-live-update to self-host updates and noticed some odd behavior.  The updated bundle download, and unzips as expected, the `buildno` property is updated in LocalStorage, but the actual bundle isn't being loaded.

The [logic](https://github.com/benallfree/cordova-live-update/blob/master/src/LiveUpdate.coffee#L134) doesn't make sense to me 

```coffeescript
loadApp: (build_id)=>
    return unless @options.beforeReboot(build_id)
    app_html = @options.appEntryPoint
    if(build_id)
      new_app_html = sprintf("%s%s/%s", @options.bundleRoot, build_id, @options.appEntryPoint)
      File.exists(app_html)
      .then(->
        console.log("New app exists", new_app_html)
        app_html = new_app_html
      )
      .fail(->
        console.log("New app is missing, using default")
      )
      .finally(->
        console.log("Navigating to ", app_html)
        window.location = app_html
      )
    else
      console.log("Navigating to ", app_html)
      window.location = app_html
```

If I set `options.appEntryPoint` to `'file:///android_asset/www/index.html'` the `File.exists(app_html)`  _then-clause_ updates `app_html` to an invalid string `file:///data/user/0/xyz/files/1488300251745/file:///android_asset/www/index.html`

If I set  `options.appEntryPoint` to `index.html` the  `File.exists(app_html)`  _fail-clause_ is called and has the effect of reloading the application  `window.location = app_html`

Should  the  `File.exists(app_html)`  be  `File.exists(new_app_html)`?   

## How does this work in practice?
It looks like the application effectively loads twice at application launch. 

The at-compile time assets  effectively bootstraps the update process.  Platform.ready() event has to fire for the cordova references to resolve.  The at-compile time assets call checkOnce, which in turn sets a property with the current build_id. Then window.location is updated with the path including the most recent bundleId (which then reloads the page with the latest assets).

Is there a way to run the latest on startup, without bootstrapping first?

**Comment by ajayambre** [comment]
@kwv Did you get this working?

**Comment by kwv** [comment]
nope. Got closer with this
https://github.com/nordnet/cordova-hot-code-push

**Comment by benallfree** [comment]
@kwv That package is now deprecated right?
