### ISSUE TITLE
Problem running liveupdate-bundle.cmd in windows

### ISSUE THREAD

**Issue by fmgomes** [benallfree/cordova-live-update#4]
Everytime I try to run node_modules\.bin\liveupdate-bundle.cmd I get the reply:

The system cannot find the path specified.

Reading the source of liveupdate-bundle.cmd, I suppose the problem is the usage of bash in windows 10, there is any prerequisite for this plugin to install bash on windows?

Thanks in advance

Fernando

**Comment by benallfree** [comment]
Hey Fernando I have no plans to support Windows, sorry. If someone else wants to we can look at this again.
